In [ ]:
# importing necessary libraries and adding the parent directory to the system path to allow imports from the numcompute package

import sys
sys.path.insert(0, "..")

In [26]:
# quickstart demo for NumCompute framework

"""
This notebook demonstrates the usage of the NumCompute framework:
- CSV loading
- Preprocessing
- Statistics
- Sorting & Ranking
- Metrics
- Optimization
- Pipeline usage
"""

'\nThis notebook demonstrates the usage of the NumCompute framework:\n- CSV loading\n- Preprocessing\n- Statistics\n- Sorting & Ranking\n- Metrics\n- Optimization\n- Pipeline usage\n'

In [ ]:
# importing necessary libraries and modules for benchmarking 

import numpy as np

from numcompute import (
    load_csv,
    StandardScaler, MinMaxScaler, OneHotEncoder, SimpleImputer,
    mean, std, quantile, histogram,   
    topk, binary_search, quickselect, 
    rank, percentile,
    accuracy, f1_score,
    grad, jacobian,                  
    Pipeline
) 


In [33]:
# loading a CSV file and printing the loaded data

data = load_csv("sample.csv", delimiter=",", skip_header=1)
print("Loaded CSV:\n", data)

Loaded CSV:
 [[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]


In [34]:
# sample data with missing values to demonstrate imputation and statistics functions

X = np.array([
    [1, 2],
    [3, np.nan],
    [5, 6]
])

print("Original Data:\n", X)

Original Data:
 [[ 1.  2.]
 [ 3. nan]
 [ 5.  6.]]


In [35]:
# handling missing values using SimpleImputer and then scaling the data using StandardScaler

imputer = SimpleImputer()
X_imp = imputer.fit_transform(X)


scaler = StandardScaler()
X_scaled = scaler.fit_transform(X_imp)

print("Processed Data:\n", X_scaled)

Processed Data:
 [[-1.22474487 -1.22474487]
 [ 0.          0.        ]
 [ 1.22474487  1.22474487]]


In [36]:
# handling missing values and then scaling the data using MinMaxScaler

mms = MinMaxScaler()
X_minmax = mms.fit_transform(X_imp)

print("MinMax Scaled:\n", X_minmax)

MinMax Scaled:
 [[0.  0. ]
 [0.5 0.5]
 [1.  1. ]]


In [37]:
# demonstrating one-hot encoding of categorical data

cat_data = np.array([
    ["A"],
    ["B"],
    ["A"]
])

encoder = OneHotEncoder()
encoded = encoder.fit_transform(cat_data)

print("One Hot Encoded:\n", encoded)

One Hot Encoded:
 [[1. 0.]
 [0. 1.]
 [1. 0.]]


In [38]:
# computing mean, median and standard deviation of the processed data using NumCompute's statistics functions

print("Mean:", mean(X_scaled))
print("Std:", std(X_scaled))
print("Median (quantile 0.5):", quantile(X_scaled, 0.5))

Mean: 0.0
Std: 0.9999999999999999
Median (quantile 0.5): 0.0


In [39]:
# histogram computation

hist, bins = histogram(arr, bins=3)
print("Histogram:", hist)
print("Bins:", bins)

Histogram: [2 1 2]
Bins: [1.         3.66666667 6.33333333 9.        ]


In [ ]:
# finding the top 3 values in the array using topk function and performing binary search for the value 7 in the sorted array

arr = np.array([5, 2, 9, 1, 7])

top_vals, idx = topk(arr, 3)
print("Top 3:", top_vals)

idx, found = binary_search(np.sort(arr), 7)
print("Binary search (7):", idx, found)


# quickselect (kth smallest element)

kth = quickselect(arr, 2)
print("2nd smallest (quickselect):", kth)

Top 3: [9 7 5]
Binary search (7): 3 True
2nd smallest (quickselect): 5


In [16]:
# now printing the ranks and percentile for the data array

data = np.array([10, 20, 20, 30])

print("Ranks:", rank(data, method="average"))
print("Percentile 50:", percentile(data, 50))

Ranks: [1.  2.5 2.5 4. ]
Percentile 50: 20.0


In [17]:
# here the accuracy and F1 score are computed for the true and predicted labels using metrics functions

y_true = [0, 1, 1, 0]
y_pred = [0, 1, 0, 0]

print("Accuracy:", accuracy(y_true, y_pred))
print("F1 Score:", f1_score(y_true, y_pred))

Accuracy: 0.75
F1 Score: 0.7894736842095457


In [44]:
# printing the gradient of the function f at the point (3.0, 4.0) using the grad function from NumCompute

f = lambda x: x[0]**2 + x[1]**2

g = grad(f, np.array([3.0, 4.0]))
print("Gradient:", g)

# jacobian of vector function

F = lambda x: np.array([x[0]**2, x[1]**2])
J = jacobian(F, np.array([3.0, 4.0]))

print("Jacobian:\n", J)


Gradient: [6. 8.]
Jacobian:
 [[6. 0.]
 [0. 8.]]


In [42]:
# fitting the pipeline to the original data and transforming it to get the final output

pipe = Pipeline([
    ("impute", SimpleImputer()),
    ("scale", StandardScaler())
])


X_pipe = pipe.fit_transform(X)
print("Pipeline Output:\n", X_pipe)

Pipeline Output:
 [[-1.22474487 -1.22474487]
 [ 0.          0.        ]
 [ 1.22474487  1.22474487]]


In [49]:
import time
import numpy as np

large_arr = np.random.rand(1000000)

# Vectorized
start = time.time()
vec_mean = np.mean(large_arr)
vec_time = time.time() - start

# Loop-based
start = time.time()
s = 0
for i in large_arr:
    s += i
loop_mean = s / len(large_arr)
loop_time = time.time() - start


print("\nBenchmark Results:\n")
print(f"{'Method':<15}{'Mean':<25}{'Time (seconds)':<15}")
print("-" * 55)
print(f"{'Vectorized':<15}{vec_mean:<25}{vec_time:<15}")
print(f"{'Loop-based':<15}{loop_mean:<25}{loop_time:<15}")


Benchmark Results:

Method         Mean                     Time (seconds) 
-------------------------------------------------------
Vectorized     0.5001100158230776       0.001165151596069336
Loop-based     0.5001100158230763       0.09347009658813477
