In [ ]:
# importing necessary libraries and modules for benchmarking

import sys
import os

sys.path.append(os.path.abspath("../.."))

In [ ]:
# quickstart demo for NumCompute framework

"""
This notebook demonstrates the usage of the NumCompute framework:
- CSV loading
- Preprocessing
- Statistics
- Sorting & Ranking
- Metrics
- Optimization
- Pipeline usage
"""

'\nThis notebook demonstrates the usage of the NumCompute framework:\n- CSV loading\n- Preprocessing\n- Statistics\n- Sorting & Ranking\n- Metrics\n- Optimization\n- Pipeline usage\n'

In [ ]:
# Importing necessary functions and classes from the NumCompute framework

import numpy as np

from numcompute import (
    load_csv,
    StandardScaler, MinMaxScaler, OneHotEncoder, SimpleImputer,
    mean, std, quantile,
    topk, binary_search,
    rank, percentile,
    accuracy, f1_score,
    grad,
    Pipeline
)

In [ ]:
# sample data with missing values to demonstrate imputation and statistics functions

X = np.array([
    [1, 2],
    [3, np.nan],
    [5, 6]
])

print("Original Data:\n", X)

Original Data:
 [[ 1.  2.]
 [ 3. nan]
 [ 5.  6.]]


In [ ]:
# handling missing values using SimpleImputer and then scaling the data using StandardScaler


imputer = SimpleImputer()
X_imp = imputer.fit_transform(X)


scaler = StandardScaler()
X_scaled = scaler.fit_transform(X_imp)

print("Processed Data:\n", X_scaled)

Processed Data:
 [[-1.22474487 -1.22474487]
 [ 0.          0.        ]
 [ 1.22474487  1.22474487]]


In [ ]:
# computing mean, median and standard deviation of the processed data using NumCompute's statistics functions

print("Mean:", mean(X_scaled))
print("Std:", std(X_scaled))
print("Median (quantile 0.5):", quantile(X_scaled, 0.5))

Mean: 0.0
Std: 0.9999999999999999
Median (quantile 0.5): 0.0


In [ ]:
# finding the top 3 values in the array using topk function and performing binary search for the value 7 in the sorted array

arr = np.array([5, 2, 9, 1, 7])

top_vals, idx = topk(arr, 3)
print("Top 3:", top_vals)

idx, found = binary_search(np.sort(arr), 7)
print("Binary search (7):", idx, found)

Top 3: [9 7 5]
Binary search (7): 3 True


In [ ]:
# now printing the ranks and percentile for the data array

data = np.array([10, 20, 20, 30])

print("Ranks:", rank(data, method="average"))
print("Percentile 50:", percentile(data, 50))

Ranks: [1.  2.5 2.5 4. ]
Percentile 50: 20.0


In [ ]:
# here the accuracy and F1 score are computed for the true and predicted labels using metrics functions

y_true = [0, 1, 1, 0]
y_pred = [0, 1, 0, 0]

print("Accuracy:", accuracy(y_true, y_pred))
print("F1 Score:", f1_score(y_true, y_pred))

Accuracy: 0.75
F1 Score: 0.7894736842095457


In [ ]:
# printing the gradient of the function f at the point (3.0, 4.0) using the grad function from NumCompute

f = lambda x: x[0]**2 + x[1]**2

g = grad(f, np.array([3.0, 4.0]))
print("Gradient:", g)

Gradient: [6. 8.]


In [ ]:
# fitting the pipeline to the original data and transforming it to get the final output

pipe = Pipeline([
    ("impute", SimpleImputer()),
    ("scale", StandardScaler())
])


X_pipe = pipe.fit_transform(X)
print("Pipeline Output:\n", X_pipe)

Pipeline Output:
 [[-1.22474487 -1.22474487]
 [ 0.          0.        ]
 [ 1.22474487  1.22474487]]
