In [1]:
import sys
import os

sys.path.append(os.path.abspath("../.."))

In [2]:
# NumCompute Quickstart Demo

"""
This notebook demonstrates the usage of the NumCompute framework:
- CSV loading
- Preprocessing
- Statistics
- Sorting & Ranking
- Metrics
- Optimization
- Pipeline usage
"""

'\nThis notebook demonstrates the usage of the NumCompute framework:\n- CSV loading\n- Preprocessing\n- Statistics\n- Sorting & Ranking\n- Metrics\n- Optimization\n- Pipeline usage\n'

In [6]:
import numpy as np

from numcompute import (
    load_csv,
    StandardScaler, MinMaxScaler, OneHotEncoder, SimpleImputer,
    mean, std, quantile,
    topk, binary_search,
    rank, percentile,
    accuracy, f1_score,
    grad,
    Pipeline
)

In [7]:
# Example data (simulate CSV)
X = np.array([
    [1, 2],
    [3, np.nan],
    [5, 6]
])

print("Original Data:\n", X)

Original Data:
 [[ 1.  2.]
 [ 3. nan]
 [ 5.  6.]]


In [8]:
# Handle missing values
imputer = SimpleImputer()
X_imp = imputer.fit_transform(X)

# Scale data
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X_imp)

print("Processed Data:\n", X_scaled)

Processed Data:
 [[-1.22474487 -1.22474487]
 [ 0.          0.        ]
 [ 1.22474487  1.22474487]]


In [9]:
print("Mean:", mean(X_scaled))
print("Std:", std(X_scaled))
print("Median (quantile 0.5):", quantile(X_scaled, 0.5))

Mean: 0.0
Std: 0.9999999999999999
Median (quantile 0.5): 0.0


In [10]:
arr = np.array([5, 2, 9, 1, 7])

top_vals, idx = topk(arr, 3)
print("Top 3:", top_vals)

idx, found = binary_search(np.sort(arr), 7)
print("Binary search (7):", idx, found)

Top 3: [9 7 5]
Binary search (7): 3 True


In [11]:
data = np.array([10, 20, 20, 30])

print("Ranks:", rank(data, method="average"))
print("Percentile 50:", percentile(data, 50))

Ranks: [1.  2.5 2.5 4. ]
Percentile 50: 20.0


In [12]:
y_true = [0, 1, 1, 0]
y_pred = [0, 1, 0, 0]

print("Accuracy:", accuracy(y_true, y_pred))
print("F1 Score:", f1_score(y_true, y_pred))

Accuracy: 0.75
F1 Score: 0.7894736842095457


In [13]:
f = lambda x: x[0]**2 + x[1]**2

g = grad(f, np.array([3.0, 4.0]))
print("Gradient:", g)

Gradient: [6. 8.]


In [14]:
pipe = Pipeline([
    ("impute", SimpleImputer()),
    ("scale", StandardScaler())
])

X_pipe = pipe.fit_transform(X)
print("Pipeline Output:\n", X_pipe)

Pipeline Output:
 [[-1.22474487 -1.22474487]
 [ 0.          0.        ]
 [ 1.22474487  1.22474487]]
